---
# tasks file for apache
---
- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Install Apache (RHEL-based)
  ansible.builtin.package:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: yes

